spring:
  control-db:
    username: sa
    password:
    driverClassName: org.h2.Driver
    jdbcUrl: jdbc:h2:mem:controldb
  target-db:
    driverClassName: org.mariadb.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost/target_db
  source-db:
    driverClassName: org.mariadb.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost/source_db
